In [1]:
print("Hello world")

Hello world


In [3]:
from numpy import *
m = matrix('1 2 3 ; 4 5 6 ; 7 8 9')
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
n = list(map(int, input().split()))

s = ''
a = 0
m = []
for i in range(len(n)//3):
    li = []
    for j in range(len(n)//3):
        li.append(n[a])
        a += 1
    m.append(li)
print(m)

1 2 3 4 5 6
[[1, 2], [3, 4]]


In [9]:
n = int(input())
li1 = []
for i in range(n):
    li2 = list(map(int, input().split()))
    li1.append(li2)
print(li1)

3
1 2 3
4 5 6
7 8 9
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [19]:
s = ''
for i in range(n):
    for j in range(n):
        s += str(li1[i][j]) + ' '
    if(i != n-1):
        s += '; '
print(s)
m1 = matrix(s)
m2 = matrix(s)
print(m1)

1 2 3 ; 4 5 6 ; 7 8 9 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
m = m1 * m2
m

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [23]:
print(diagonal(m))

[ 30  81 150]


In [25]:
f = m.flatten()
f

matrix([[ 30,  36,  42,  66,  81,  96, 102, 126, 150]])

In [30]:
f.reshape(3, 3)

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [61]:
li = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
ma = matrix(li)
ma

matrix([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [62]:
r = ma.flatten()
r

matrix([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [65]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr.reshape(2, 2, 3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [66]:
arr.reshape(2, 2, -1)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [1]:
x, y, z = 1, 2, 3
print(x, y, z)

1 2 3


In [3]:
3**3

27

In [4]:
x = "python"
y = "is"
z = "awsome"
print(x, y, z)

python is awsome


In [6]:
print(x + y + z)

pythonisawsome


In [19]:
import re
s = "This is, my ;name"
t = s.split(' ')
s = ''
for i in t:
    s += i + ','
print(s)
re.split(',|;', s)

This,is,,my,;name,


['This', 'is', '', 'my', '', 'name', '']

In [29]:
a = ""
for i in "hello":
    b = str(ord(i))
    a += "\\" + b
print(a)
print(type(a))

\104\101\108\108\111
<class 'str'>


In [31]:
txt = "\110\145\154\154\157"
print(type(txt))
txt

<class 'str'>


'Hello'

In [32]:
a = "abcd"
print(len(a))

4


In [4]:
li = [1, 2, 3, 4, 5, 6, 7]
a, b, c, *d = li
print(a, b, c, d)

1 2 3 [4, 5, 6, 7]


In [16]:
a = 2
b = 330
print("A") if a > b else print("B")

B


In [15]:
a = 330
b = 330
print("A") if a > b else print("=") if a == b else print("B")

=


# Arbitary Arguments *args
If the number of arguments is unknown, add a * before the parameter name:

In [19]:
def my_function(*kids):
  print("The youngest child is " + kids[2])

my_function("Emil", "Tobias", "Linus")

The youngest child is Linus


# Arbitrary Keyword Arguments, **kwargs
If the number of keyword arguments is unknown, add a double ** before the parameter name:

In [22]:
def my_function(**kid):
  print("His last name is " + kid["lname"])

my_function(fname = "Tobias", lname = "Refsnes")

His last name is Refsnes


# Default Parameter Value
If we call the function without argument, it uses the default value:

In [23]:
def my_function(country = "Norway"):
  print("I am from " + country)

my_function("Sweden")
my_function("India")
my_function()
my_function("Brazil")

I am from Sweden
I am from India
I am from Norway
I am from Brazil


# Recursion

In [24]:
def tri_recursion(k):
  if(k > 0):
    result = k + tri_recursion(k - 1)
    print(result)
  else:
    result = 0
  return result

print("\n\nRecursion Example Results")
tri_recursion(6)




Recursion Example Results
1
3
6
10
15
21


21

# Decimals

In [1]:
price = 49
g = 45
txt = "The price is {0:.2f} dollars"
print(txt.format(price, g))

The price is 49.00 dollars


In [26]:
quantity = 3
itemno = 567
price = 49
myorder = "I want {} pieces of item number {} for {:.2f} dollars."
print(myorder.format(quantity, itemno, price))

I want 3 pieces of item number 567 for 49.00 dollars.


# Lambda

In [29]:
x = lambda a : a + 10
print(x(5))

15


In [28]:
def myfunc(n):
  print(n)
  return lambda a : a * n

mydoubler = myfunc(2)

print(mydoubler(11))

2
22


# The __str__() Function
The string representation of an object WITHOUT the __str__() function:

In [30]:
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

p1 = Person("John", 36)

print(p1)


The string representation of an object WITH the __str__() function:

In [33]:
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def __str__(self):
    return f"{self.name} {self.age}"

p1 = Person("John", 36)

print(p1)

John 36


# The self Parameter
The self parameter is a reference to the current instance of the class, and is used to access variables that belongs to the class.

It does not have to be named self , you can call it whatever you like, but it has to be the first parameter of any function in the class:

In [34]:
class Person:
  def __init__(mysillyobject, name, age):
    mysillyobject.name = name
    mysillyobject.age = age

  def myfunc(abc):
    print("Hello my name is " + abc.name)

p1 = Person("John", 36)
p1.myfunc()

Hello my name is John


# Inhereance

In [35]:
class Person:
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname

  def printname(self):
    print(self.firstname, self.lastname)

class Student(Person):
  pass

x = Student("Mike", "Olsen")
x.printname()

Mike Olsen


When you add the __init__() function, the child class will no longer inherit the parent's __init__() function.

Note: The child's __init__() function overrides the inheritance of the parent's __init__() function.

To keep the inheritance of the parent's __init__() function, add a call to the parent's __init__() function:

In [36]:
class Person:
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname

  def printname(self):
    print(self.firstname, self.lastname)

class Student(Person):
  def __init__(self, fname, lname):
    Person.__init__(self, fname, lname)

x = Student("Mike", "Olsen")
x.printname()

Mike Olsen


# Use the super() Function
Python also has a super() function that will make the child class inherit all the methods and properties from its parent:

In [37]:
class Person:
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname

  def printname(self):
    print(self.firstname, self.lastname)

class Student(Person):
  def __init__(self, fname, lname):
    super().__init__(fname, lname)

x = Student("Mike", "Olsen")
x.printname()


Mike Olsen


# Iterators

In [39]:
class MyNumbers:
  def __iter__(self):
    self.a = 1
    return self

  def __next__(self):
    if self.a <= 20:
      x = self.a
      self.a += 1
      return x
    else:
      raise StopIteration

myclass = MyNumbers()
myiter = iter(myclass)

for x in myiter:
  print(x, end = " ")


1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 

# Polymorphism

In [40]:
class Car:
  def __init__(self, brand, model):
    self.brand = brand
    self.model = model

  def move(self):
    print("Drive!")

class Boat:
  def __init__(self, brand, model):
    self.brand = brand
    self.model = model

  def move(self):
    print("Sail!")

class Plane:
  def __init__(self, brand, model):
    self.brand = brand
    self.model = model

  def move(self):
    print("Fly!")

car1 = Car("Ford", "Mustang")       #Create a Car class
boat1 = Boat("Ibiza", "Touring 20") #Create a Boat class
plane1 = Plane("Boeing", "747")     #Create a Plane class

for x in (car1, boat1, plane1):
  x.move()


Drive!
Sail!
Fly!


In [41]:
class Vehicle:
  def __init__(self, brand, model):
    self.brand = brand
    self.model = model

  def move(self):
    print("Move!")

class Car(Vehicle):
  pass

class Boat(Vehicle):
  def move(self):
    print("Sail!")

class Plane(Vehicle):
  def move(self):
    print("Fly!")

car1 = Car("Ford", "Mustang") #Create a Car object
boat1 = Boat("Ibiza", "Touring 20") #Create a Boat object
plane1 = Plane("Boeing", "747") #Create a Plane object

for x in (car1, boat1, plane1):
  print(x.brand)
  print(x.model)
  x.move()


Ford
Mustang
Move!
Ibiza
Touring 20
Sail!
Boeing
747
Fly!


# Regular Expression Split

In [24]:
import re

#Split the string at the two white-space character:

txt = "The rain in Spain"
x = re.split("\s", txt, 2)
print(x)


['The', 'rain', 'in Spain']


In [2]:
import re

#Replace the first two occurrences of a white-space character with the digit 9:

txt = "The rain in Spain"
x = re.sub("\s", "9", txt, 2)
print(x)


The9rain9in Spain


In [1]:
count = 5
def some_method():
    global count
    count = count + 1
    print(count)
some_method()

6


# Switch statement

In [5]:
def monday():
    return "monday"
def tuesday():
    return "tuesday"
def wednesday():
    return "wednesday"
def default():
    return "Incorrect day"
switcher = {
    1: monday,
    2: tuesday,
    3: wednesday
}

def switch(number):
    return switcher.get(number, default)()

print(switch(1))

monday


In [7]:
import pymongo

In [20]:
a = "Vamshi"
k = "krishna"
print("{1} {0}".format(a, k))

krishna Vamshi


In [21]:
a = "Vamshi"
k = "krishna"
print("{k} {a}".format(a="100", k=200))

200 100


In [23]:
a = "Vamshi"
k = "krishna"
print(f"{a} {k}")

Vamshi krishna


In [30]:
li = [*range(0, 10, 2)]
li

[0, 2, 4, 6, 8]

In [34]:
li = ["vamshi", "krishna", "smart"]
l = ",".join(li)
l

'vamshi,krishna,smart'

In [35]:
l = tuple([1, 2, 3, 4, 5])
l

(1, 2, 3, 4, 5)

In [37]:
s = set([5, 4, 3, 2, 1, 3])
s

{1, 2, 3, 4, 5}

In [39]:
li = list([1, 3, 2, 4, 7, 5 ,5])
li

[1, 3, 2, 4, 7, 5, 5]