In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [2]:
print(arr)

[1 2 3 4 5]


In [3]:
arr.ndim

1

In [4]:
arr.shape

(5,)

In [6]:
arr2 = np.array([[2, 3, 4, 5], [6, 7, 8, 9]])
arr2

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [7]:
arr2.ndim

2

In [8]:
arr3 = np.array([[2, 3, 4, 5], [6, 7, 8, 9], [3, 5, 7, 8]])
arr3.ndim

2

In [9]:
arr3.shape

(3, 4)

In [10]:
arr3

array([[2, 3, 4, 5],
       [6, 7, 8, 9],
       [3, 5, 7, 8]])

In [11]:
arr4 = np.array([[[2, 3, 4, 5], [6, 7, 8, 9], [3, 5, 7, 8]], [[3, 4, 5, 6], [5, 6, 7, 8], [1, 2, 45, 6]]])
arr4.ndim

3

In [12]:
arr4

array([[[ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [ 3,  5,  7,  8]],

       [[ 3,  4,  5,  6],
        [ 5,  6,  7,  8],
        [ 1,  2, 45,  6]]])

In [15]:
arr4.shape

(2, 3, 4)

In [16]:
arr3.shape

(3, 4)

In [17]:
arr3.dtype

dtype('int32')

In [18]:
arr = np.array([1, 2, 3, 4, 5], dtype = 'int16')
arr.dtype

dtype('int16')

In [19]:
arr.itemsize # 1 byte = 8 bits, where ar is int 16 bits

2

In [21]:
arr2.itemsize # 4 bytes where default size is 4 bytes = int 32 bits

4

In [25]:
arr3.size # total number of values

12

In [26]:
arr3.itemsize

4

In [28]:
arr3.size * arr3.itemsize

48

In [30]:
arr3.nbytes # arr3.nbytes = arr3.size * arr3.itemsize

48

In [36]:
arrfloat = np.array([[2.0, 3.1, 4.0, 5], [6.7, 7.0, 8.0, 9.5]])
arrfloat

array([[2. , 3.1, 4. , 5. ],
       [6.7, 7. , 8. , 9.5]])

In [35]:
arrfloat.itemsize # float is of 8 bytes

8

In [33]:
arrfloat.dtype

dtype('float64')

In [37]:
arrfloat

array([[2. , 3.1, 4. , 5. ],
       [6.7, 7. , 8. , 9.5]])

In [38]:
arrfloat[1, 2] # indexing [row, column]

8.0

In [39]:
arrfloat[1, -1] # indexing

9.5

In [42]:
arrfloat[0, :] # get the first row

array([2. , 3.1, 4. , 5. ])

In [43]:
arrfloat[:, 2] # get the 3rd column

array([4., 8.])

In [44]:
arrn = np.array([[2, 3, 4, 5, 4, 6, 3, 4], [6, 7, 8, 9, 7, 8, 9, 9]])
arrn

array([[2, 3, 4, 5, 4, 6, 3, 4],
       [6, 7, 8, 9, 7, 8, 9, 9]])

In [46]:
arrn[:, 2:5] #get from 3rd column to 5th column

array([[4, 5, 4],
       [8, 9, 7]])

In [47]:
arrn[0, 1:5] # first column 4 elements starting from second position

array([3, 4, 5, 4])

In [49]:
arrn[0, ::-1]

array([4, 3, 6, 4, 5, 4, 3, 2])

In [52]:
arrn[0, ::2] #jump by 2

array([2, 4, 4, 3])

In [53]:
arrn[0, 1:-1:2]

array([3, 5, 6])

In [56]:
#changing values in numpy rows(chaning the second element of first list)
arrn[0, 1] = 13
arrn

array([[ 2, 13,  4,  5,  4,  6,  3,  4],
       [ 6,  7,  8,  9,  7,  8,  9,  9]])

In [58]:
#change values in numpy columns(change the last column to all 10)
arrn[:, 7] = 10
arrn

array([[ 2, 13,  4,  5,  4,  6,  3, 10],
       [ 6,  7,  8,  9,  7,  8,  9, 10]])

In [60]:
arrn[:, 7] = [10, 20] #Change last column to 10 and 20
arrn

array([[ 2, 13,  4,  5,  4,  6,  3, 10],
       [ 6,  7,  8,  9,  7,  8,  9, 20]])

In [61]:
arr4 = np.array([[[2, 3, 4, 5], [6, 7, 8, 9], [3, 5, 7, 8]], [[3, 4, 5, 6], [5, 6, 7, 8], [1, 2, 45, 6]]])
arr4.ndim

3

In [62]:
arr4

array([[[ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [ 3,  5,  7,  8]],

       [[ 3,  4,  5,  6],
        [ 5,  6,  7,  8],
        [ 1,  2, 45,  6]]])

In [65]:
arr4[0, 1, :] #get the second row in first array

array([6, 7, 8, 9])

In [64]:
arr4[0, :, 1] #get the second column in second aray

array([3, 7, 5])

In [68]:
arr4[0, 1, 2]

8

In [69]:
arr4[:, 0, :]

array([[2, 3, 4, 5],
       [3, 4, 5, 6]])

In [71]:

arr4[:, 0, :] = [[1, 2, 3, 4], [5, 6, 7, 8]] #changing value in 3 dimensional array
arr4

array([[[ 1,  2,  3,  4],
        [ 6,  7,  8,  9],
        [ 3,  5,  7,  8]],

       [[ 5,  6,  7,  8],
        [ 5,  6,  7,  8],
        [ 1,  2, 45,  6]]])

In [72]:
arr4.shape

(2, 3, 4)

In [75]:
li = [*range(6)]
li

[0, 1, 2, 3, 4, 5]

In [83]:
arrd = np.zeros((3, 2, 2, 2))
arrd.ndim

4

In [82]:
arrd.ndim

4

In [88]:
ones = np.ones((4, 2, 2), dtype = 'int16')
ones

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int16)

In [89]:
ones.dtype

dtype('int16')

In [93]:
fullnp = np.full((2, 2), 78, dtype = 'float32')
fullnp

array([[78., 78.],
       [78., 78.]], dtype=float32)

In [97]:
arr3 = np.array([[2, 3, 4, 5], [6, 7, 8, 9], [3, 5, 7, 8]])
np.full_like(arr3, 10) #takes the shape from arr3

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [99]:
arr3 = np.array([[2, 3, 4, 5], [6, 7, 8, 9], [3, 5, 7, 8]])
np.full(arr3.shape, 10) #takes the shape from arr3

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [100]:
np.random.rand(4, 2)

array([[0.57840738, 0.27097677],
       [0.03858091, 0.75756238],
       [0.00222069, 0.12858178],
       [0.92132928, 0.84605078]])

In [104]:
np.random.random_sample(arr3.shape)

array([[0.97662471, 0.08538441, 0.30069812, 0.15093436],
       [0.5025469 , 0.35934287, 0.55355445, 0.76240167],
       [0.61761537, 0.06710815, 0.49117842, 0.32905808]])

In [106]:
np.random.randint(0, 10, size=(3, 4))

array([[6, 2, 1, 3],
       [6, 0, 9, 9],
       [1, 9, 5, 0]])

In [107]:
#The identity matrix, is also a square matrix n*n
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [113]:
# Repeat an array
a = np.array([[1, 2, 3]])
a1 = np.repeat(a, 3, axis = 1)
a1

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [114]:
a = np.array([[1, 2, 3]])
a1 = np.repeat(a, 3, axis = 0)
a1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [121]:
# Print gussing matrix
ones = np.ones((5, 5))
print(ones)

zeros = np.zeros((3, 3))
zeros[1, 1] = 9
print(zeros)

ones[1:4, 1:4] = zeros
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [127]:
ones[1:4, 0:3] = zeros
print(ones)

[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1.]
 [0. 9. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [130]:
# copy numpy aray
a = np.array([1, 2, 3, 4])
b = a.copy()  # If any changes made in a or b will not affect b
print(a, b)

[1 2 3 4] [1 2 3 4]


In [131]:
# Operators with numpy
a*2

array([2, 4, 6, 8])

In [132]:
a-1

array([0, 1, 2, 3])

In [133]:
a-2

array([-1,  0,  1,  2])

In [134]:
a + 3

array([4, 5, 6, 7])

In [137]:
c = a/2
c.dtype

dtype('float64')

In [139]:
a += 2
a

array([5, 6, 7, 8])

In [141]:
a *= 3
a

array([45, 54, 63, 72])

In [143]:
#math with arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
a + b

array([ 6,  8, 10, 12])

In [144]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [149]:
ones = np.ones((2, 3))
print(ones)

zeros = np.full((3, 2), 2)
print(zeros)

np.matmul(ones, zeros)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [154]:
# Linear regression
# Find the determination of matrix(https://www.cuemath.com/algebra/determinants/)
id = np.identity(3)
print(id)

np.linalg.det(id)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [155]:
ar = np.array([[3, 1, 1], [4, -2, 5], [2, 8, 7]])

np.linalg.det(ar)

-144.0

In [156]:
# Statistics
arr = np.array([[1, 2, 3], [1, 3, 5]])
arr

array([[1, 2, 3],
       [1, 3, 5]])

In [157]:
np.min(arr)

1

In [158]:
np.max(arr)

5

In [162]:
np.min(arr, axis = 0) # Gives the minumum sum row, axis = 0 => row

array([1, 2, 3])

In [164]:
np.max(arr, axis = 1) # Gives the maximum sum column, axis = 1 => column

array([3, 5])

In [169]:
np.sum(arr, axis = 1) # Sum of rows, count of columns

array([6, 9])

In [170]:
np.sum(arr, axis = 0) # sum of columns, count of columns

array([2, 5, 8])

In [171]:
np.sum(arr)

15

In [174]:
# Reorganizing arrays
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape(4, 2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [175]:
after2 = before.reshape(2, 2, 2)
print(after2)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [179]:
# Vertical Stack
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

c = np.vstack([a, b, b, a])
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [181]:
d = np.hstack([a,b])
d

array([1, 2, 3, 4, 5, 6, 7, 8])

In [186]:
# Horizantal stack
ones = np.ones((2, 4))
zeros = np.zeros((2, 2))

np.hstack((ones, zeros))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [197]:
x = np.genfromtxt("data.txt", delimiter = ", ")
x

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.,  0., 11., 22., 33.],
       [ 0.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.,  9.,  8.,  7.],
       [ 5.,  4.,  3.,  2., 19.,  8.,  7.,  6.,  0.,  1., 33., 44., 55.]])

In [221]:
y = x.astype("int32")
y

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9,  0, 11, 22, 33],
       [ 0,  9,  8,  7,  6,  5,  4,  3,  2,  1,  9,  8,  7],
       [ 5,  4,  3,  2, 19,  8,  7,  6,  0,  1, 33, 44, 55]])

In [202]:
#Boolean masking and advance indexing
#Enter true if the value is greater than 10
y > 10

array([[False, False, False, False, False, False, False, False, False,
        False,  True,  True,  True],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False],
       [False, False, False, False,  True, False, False, False, False,
        False,  True,  True,  True]])

In [204]:
# get values greater than 10
y[y > 10]

array([11, 22, 33, 19, 33, 44, 55])

In [205]:
# you can index with a list in numpy
ab = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
ab[[1, 2, 8]]

array([2, 3, 9])

In [214]:
# return true if any column has value more than 10 (compare rowwise)
np.any(y>10, axis = 0)

array([False, False, False, False,  True, False, False, False, False,
       False,  True,  True,  True])

In [215]:
# return true if any row has value more than 10 (compare column wise)
np.any(y>10, axis = 1)

array([ True, False,  True])

In [217]:
# return true if all row has value more than 10 (compare column wise)
np.all(y>10, axis = 0)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [224]:
(~(y>10) & (y < 20)) # check the value between 10 and 20

array([[False, False, False, False, False, False, False, False, False,
        False,  True, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False],
       [False, False, False, False,  True, False, False, False, False,
        False, False, False, False]])

In [226]:
(~(y>10) & (y < 20)) # check the value NOT between 10 and 20

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True,  True,
         True, False, False, False]])

In [231]:
x = np.genfromtxt("numbers.txt", delimiter=", ").astype("int32")
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [232]:
x[[0, 1, 2, 3], [1, 2, 3, 4]] # backslash indexed with slash

array([ 2,  8, 14, 20])

In [233]:
for i in x:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]
[16 17 18 19 20]
[21 22 23 24 25]
[26 27 28 29 30]


In [234]:
len(x)

6

In [237]:
x[[0, 4, 5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])